### PR TITLE
Fix GCE deployment and arktos-up to correctly enable Vertical Scaling feature

### PR DESCRIPTION
**Pull request by vinaykul**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: This PR fixes kube-up and arktos-up scripts to correctly bring up cluster with Vertical Scaling feature enabled. This is now controlled by the boolean flag ENABLE_POD_VERTICAL_SCALING. 

**Which issue(s) this PR fixes**: #975 

Fixes #

**Special notes for your reviewer**: 

**Does this PR introduce a user-facing change?**:

```release-note
To enable vertical scaling, use

GCE: ENABLE_POD_VERTICAL_SCALING=true ./cluster/kube-up.sh

Local: ENABLE_POD_VERTICAL_SCALING=true ./hack/arktos-up.sh

```

### CODE REVIEW

**Review by yb01 — APPROVED** [review]
/lgtm

**Review by sonyafenge — APPROVED** [review]
/LGTM

**Pull request merged**
