### PR TITLE
Use insecure-port only for scaleout, cleanup common.sh

### PR DESCRIPTION
**Pull request by vinaykul**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: The second create-kubeconfig function is a duplicate, identical to the first function. It is not required. Tested by deploying cluster with kube-up & start-kubemark.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by chenqianfzh — APPROVED** [review]

**Comment by chenqianfzh** [comment]
lgtm

**Review by yb01 — APPROVED** [review]
/lgtm

**Review by yb01 — APPROVED** [review]
/lgtm

**Pull request merged**
