### PR TITLE
Support multiple RPs in Mizar node controller

### PR DESCRIPTION
**Pull request by Sindica**
Tested with Arktos-up with and without Mizar plugin.

### CODE REVIEW

**Review by h-w-chen — APPROVED** [review]
LGTM.
suggest to add adequate description to PR.

**Comment by yb01** [comment]
should this PR go to the 130 branch first ?

**Comment by Sindica** [comment]
> should this PR go to the 130 branch first ?

This change is independent and self enclosure. Go to master directly can reduce further merging effort.

**Review by yb01 — APPROVED** [review]
/lgtm

**Pull request merged**
