### PR TITLE
1.18 improvement kcm metadataclient

### PR DESCRIPTION
**Pull request by Sindica**
Ported the following changes from 1.18:
. Add a metadata client to client-go that can read PartialObjectMetadata
. Update namespace controller & garbage controller to use the metadata client

Arktos changes:
. Add multi-tenancy changes to metadata client, fix UT & integration test
. Copyright fix

Reason:
. Performance improvement from 1.18: "the metadata client uses protobuf and returns only a subset of object
data (the metadata) which allows operations that act only on objects generically to work much faster. "
. Vendor dependency changes required in https://github.com/CentaurusInfra/arktos/issues/923

### CODE REVIEW

**Review by chenqianfzh — APPROVED** [review]
I verified the code change with the multi-tenancy e2e test and it passed.

**Comment by sonyafenge** [comment]
This PR is also part of kube-openapi upgrade: #923

**Review by sonyafenge — APPROVED** [review]
/LGTM

**Pull request merged**
